import type { Metadata } from "next";
import { Poppins, Bagel_Fat_One } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { getUser } from "@/data/dal/user/getUser";
import { getSessionUserId } from "@/data/auth/getSessionUserId";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

const bagelFatOne = Bagel_Fat_One({
  variable: "--font-bagel",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let currentUser = null;

  try {
    const id = await getSessionUserId();
    currentUser = await getUser(id);
  } catch (e) {}

  return (
    <html
      lang="en"
      className={`${poppins.variable} ${bagelFatOne.variable} min-h-screen antialiased scroll-smooth overscroll-x-none`}>
      <body className="min-h-screen flex flex-col overscroll-x-none justify-between ">
        {" "}
        <NavBar mode={currentUser ? "signedin" : "notSignedIn"} />
        <main className="flex-1 bg-background pt-16"> {children}</main>
        <Footer />
      </body>
    </html>
  );
}
